import type {
   ContactForm,
   QuoteRequest,
   Transaction,
   EnergyClient,
} from "./types";

export const MOCK_CONTACT_FORMS: ContactForm[] = [
   {
      id: 1,
      name: "Ana García",
      email: "ana.garcia@gmail.com",
      phone: "+1 (809) 555-0111",
      topic: "Consulta sobre instalación residencial",
      date: "2025-07-10",
      status: "Pendiente",
   },
   {
      id: 2,
      name: "Pedro Martínez",
      email: "pedro@empresa.com",
      phone: "+1 (849) 555-0122",
      topic: "Mantenimiento de paneles solares",
      date: "2025-07-09",
      status: "Revisado",
   },
   {
      id: 3,
      name: "María López",
      email: "maria.lopez@gmail.com",
      phone: "+1 (829) 555-0133",
      topic: "Falla en inversor del sistema",
      date: "2025-07-08",
      status: "Respondido",
   },
   {
      id: 4,
      name: "Roberto Díaz",
      email: "roberto@negocio.com",
      phone: "+1 (809) 555-0144",
      topic: "Cotización para local comercial",
      date: "2025-07-07",
      status: "Pendiente",
   },
   {
      id: 5,
      name: "Carmen Reyes",
      email: "carmen.reyes@gmail.com",
      phone: "+1 (849) 555-0155",
      topic: "Servicio de limpieza de paneles",
      date: "2025-07-06",
      status: "Revisado",
   },
   {
      id: 6,
      name: "José Fernández",
      email: "jose.f@outlook.com",
      phone: "+1 (829) 555-0166",
      topic: "Ampliación de sistema existente",
      date: "2025-07-05",
      status: "Pendiente",
   },
];

export const MOCK_QUOTE_REQUESTS: QuoteRequest[] = [
   {
      id: 1,
      name: "Comercial El Sol SRL",
      email: "contacto@elsol.com",
      phone: "+1 (809) 555-0201",
      distributor: "Edenorte",
      topic: "Instalación comercial 25 kWp",
      date: "2025-07-10",
      status: "En proceso",
   },
   {
      id: 2,
      name: "Familia García",
      email: "familia.garcia@gmail.com",
      phone: "+1 (849) 555-0202",
      distributor: "Edesur",
      topic: "Sistema residencial 8 kWp",
      date: "2025-07-09",
      status: "Completado",
   },
   {
      id: 3,
      name: "Hotel Plaza Central",
      email: "gerencia@hotelplaza.com",
      phone: "+1 (829) 555-0203",
      distributor: "Edenorte",
      topic: "Sistema de gran escala 50 kWp",
      date: "2025-07-08",
      status: "Pendiente",
   },
   {
      id: 4,
      name: "Taller Mecánico Rápido",
      email: "taller.rapido@gmail.com",
      phone: "+1 (809) 555-0204",
      distributor: "Edeeste",
      topic: "Sistema pequeño 5 kWp",
      date: "2025-07-07",
      status: "En proceso",
   },
   {
      id: 5,
      name: "Edificio Centro Empresarial",
      email: "admin@centroempresarial.com",
      phone: "+1 (849) 555-0205",
      distributor: "Edesur",
      topic: "Sistema corporativo 30 kWp",
      date: "2025-07-05",
      status: "Pendiente",
   },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
   {
      id: 1,
      description: "Instalación residencial 8.25 kWp — Familia García",
      amount: 180000,
      type: "income",
      date: "2025-07-09",
      category: "Instalación",
   },
   {
      id: 2,
      description: "Compra de paneles solares — Lote 12 uds",
      amount: 85000,
      type: "expense",
      date: "2025-07-08",
      category: "Materiales",
   },
   {
      id: 3,
      description: "Instalación comercial 25 kWp — Comercial El Sol",
      amount: 450000,
      type: "income",
      date: "2025-07-07",
      category: "Instalación",
   },
   {
      id: 4,
      description: "Materiales de estructura e instalación",
      amount: 35000,
      type: "expense",
      date: "2025-07-06",
      category: "Materiales",
   },
   {
      id: 5,
      description: "Servicio de limpieza — Hotel Plaza Central",
      amount: 25000,
      type: "income",
      date: "2025-07-05",
      category: "Mantenimiento",
   },
   {
      id: 6,
      description: "Mantenimiento de vehículo de trabajo",
      amount: 12000,
      type: "expense",
      date: "2025-07-04",
      category: "Operaciones",
   },
];

export const MOCK_ENERGY_CLIENTS: EnergyClient[] = [
   {
      id: 1,
      name: "Familia García",
      location: "Santiago de los Caballeros",
      systemKwp: 8.25,
      dailyKwh: 38.2,
      monthlyKwh: 1146,
      monthlySavings: 6876,
   },
   {
      id: 2,
      name: "Hotel Plaza Central",
      location: "Santiago de los Caballeros",
      systemKwp: 50.0,
      dailyKwh: 231.5,
      monthlyKwh: 6945,
      monthlySavings: 41670,
   },
   {
      id: 3,
      name: "Laboratorio de Patología",
      location: "Santo Domingo",
      systemKwp: 58.0,
      dailyKwh: 268.4,
      monthlyKwh: 8052,
      monthlySavings: 48312,
   },
   {
      id: 4,
      name: "Casa Familia Rodríguez",
      location: "La Vega",
      systemKwp: 6.27,
      dailyKwh: 29.0,
      monthlyKwh: 870,
      monthlySavings: 5220,
   },
];
