export const REGIONS = [
   { id: 'azua', regionName: 'Azua', sunhours: 0 },
   { id: 'bahoruco', regionName: 'Bahoruco', sunhours: 0 },
   { id: 'barahona', regionName: 'Barahona', sunhours: 0 },
   { id: 'dajabon', regionName: 'Dajabón', sunhours: 0 },
   { id: 'distritoNacional', regionName: 'Distrito Nacional', sunhours: 0 },
   { id: 'duarte', regionName: 'Duarte', sunhours: 0 },
   { id: 'elSeibo', regionName: 'El Seibo', sunhours: 0 },
   { id: 'eliasPina', regionName: 'Elías Piña', sunhours: 0 },
   { id: 'espaillat', regionName: 'Espaillat', sunhours: 0 },
   { id: 'hatoMayor', regionName: 'Hato Mayor', sunhours: 0 },
   { id: 'independencia', regionName: 'Independencia', sunhours: 0 },
   { id: 'laAltagracia', regionName: 'La Altagracia', sunhours: 0 },
   { id: 'laRomana', regionName: 'La Romana', sunhours: 0 },
   { id: 'laVega', regionName: 'La Vega', sunhours: 0 },
   { id: 'mariaTrinidadSanchez', regionName: 'María Trinidad Sánchez', sunhours: 0 },
   { id: 'monseñorNouel', regionName: 'Monseñor Nouel', sunhours: 0 },
   { id: 'monteCristi', regionName: 'Monte Cristi', sunhours: 0 },
   { id: 'montePlata', regionName: 'Monte Plata', sunhours: 0 },
   { id: 'pedernales', regionName: 'Pedernales', sunhours: 0 },
   { id: 'peravia', regionName: 'Peravia', sunhours: 0 },
   { id: 'puertoPlata', regionName: 'Puerto Plata', sunhours: 0 },
   { id: 'samana', regionName: 'Samaná', sunhours: 0 },
   { id: 'sanchezRamirez', regionName: 'Sánchez Ramírez', sunhours: 0 },
   { id: 'sanCristobal', regionName: 'San Cristóbal', sunhours: 0 },
   { id: 'sanJoseDeOcoa', regionName: 'San José de Ocoa', sunhours: 0 },
   { id: 'sanJuan', regionName: 'San Juan', sunhours: 0 },
   { id: 'sanPedroDeMacoris', regionName: 'San Pedro de Macorís', sunhours: 0 },
   { id: 'santiago', regionName: 'Santiago', sunhours: 0 },
   { id: 'santiagoRodriguez', regionName: 'Santiago Rodríguez', sunhours: 0 },
   { id: 'santoDomingo', regionName: 'Santo Domingo', sunhours: 0 },
   { id: 'valverde', regionName: 'Valverde', sunhours: 0 }
];
